### ISSUE TITLE
node配置正常，在浏览器打开地址后 ，显示一片空白

### ISSUE THREAD

**Issue by vimer** [stonexer/wechatBot#10]

**Comment by stonexer** [comment]
server 和 浏览器 都有啥报错么。有没有 build 一下啊。

**Comment by vimer** [comment]
报 app.js 404

Original Message
Sender:SToneXnotifications@github.com
Recipient:stonexer/wechatBotwechatBot@noreply.github.com
Cc:vimeremacs@vimer.org
Date:Monday, Mar 7, 2016 12:05
Subject:Re: [wechatBot] node配置正常，在浏览器打开地址后 ，显示一片空白 (#10)

server 和 浏览器 都有啥报错么。有没有 build 一下啊

**Comment by stonexer** [comment]
抱歉，需要 build 一下。可以看下更新的 README。

**Comment by vimer** [comment]
恩，另外我 点击 箭头对TA自动回复，然后刷新页面 ，此时箭头变成灰色状态，但是还是可以对他进行自动回复的，再点击变绿就变成取消了

Original Message
Sender:SToneXnotifications@github.com
Recipient:stonexer/wechatBotwechatBot@noreply.github.com
Cc:vimeremacs@vimer.org
Date:Monday, Mar 7, 2016 12:08
Subject:Re: [wechatBot] node配置正常，在浏览器打开地址后 ，显示一片空白 (#10)

抱歉，需要 build 一下。可以看下更新的 README。

**Comment by stonexer** [comment]
嗯啊。这是个bug。感谢反馈！

**Comment by stonexer** [comment]
7922342f2ebde65a8978c37ab461be1fac8d8917

fix 箭头在刷新页面后的错误显示
