### ISSUE TITLE
时常报state Selector错误

### ISSUE THREAD

**Issue by fanly** [stonexer/wechatBot#12]
wechat Error: 未知的State Selector
    at /Users/wuhaiping/git/learning/wechat/wechatBot/node_modules/wechat4u/lib/wechat.js:535:19
    at process._tickCallback (node.js:406:9) +12s

**Comment by spacelan** [comment]
@stonexer 
https://github.com/nodeWechat/wechat4u/blob/master/src/wechat.js#L494
这里是不是考虑一下不抛错？

**Comment by stonexer** [comment]
@spacelan 去了吧。我本来是报给我自己看的😄

**Comment by stonexer** [comment]
在 wechat4u 里修改了。和这个项目无关，先关了😄
