### ISSUE TITLE
不能多用户登录

### ISSUE THREAD

**Issue by fanly** [stonexer/wechatBot#13]
如题，不能多用户登录。求帮忙

**Comment by stonexer** [comment]
```
        是指什么的多用户啊。单个浏览器么？
```

**Comment by fanly** [comment]
我部署到了服务器了，我登录操作后，另一个人后登录，我的状态就不存在了，相当于后一个人顶了我。

**Comment by stonexer** [comment]
这么大的 bug！感谢感谢！正在研究。

**Comment by stonexer** [comment]
不过这个 bug 是 wechat4u 的哈。就在这儿跟踪吧。

**Comment by stonexer** [comment]
IcL1hNwEhg== https://webpush2.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck webwx_data_ticket=AQcHu38tHeJYHJVvsP3p1dxj

新用户登陆

we6YPbVw8A== https://webpush2.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck webwx_data_ticket=AQdmR6cz6BjjV7XfIVEjhDyR

旧的变成了

IcL1hNwEhg== https://webpush2.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck webwx_data_ticket=AQdmR6cz6BjjV7XfIVEjhDyR

**Comment by stonexer** [comment]
@fanly 
升级下 wechat4u 到 0.2.5 应该就没问题了

**Comment by fanly** [comment]
解决了，太棒了
