### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by cbwang2016** [stonexer/wechatBot#18]
npm ERR! peerinvalid The package babel-runtime does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vue-loader@8.5.2 wants babel-runtime@^6.0.0

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/<User>/Documents/wechatBot-master
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/<User>/Documents/wechatBot-master/npm-debug.log
npm ERR! not ok code 0

log中的内容：
cat ./npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.6
3 info using node@v0.10.42
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/home/<User>/Documents/wechatBot-master',
5 verbose install   [ 'axios',
5 verbose install     'body-parser',
5 verbose install     'debug',
5 verbose install     'es6-promise',
5 verbose install     'express',
5 verbose install     'jade',
5 verbose install     'vue',
5 verbose install     'vue-resource',
5 verbose install     'vue-router',
5 verbose install     'vue-strap',
5 verbose install     'wechat4u',
5 verbose install     'babel-core',
5 verbose install     'babel-loader',
5 verbose install     'babel-plugin-transform-runtime',
5 verbose install     'babel-preset-es2015',
5 verbose install     'babel-preset-stage-2',
5 verbose install     'babel-runtime',
5 verbose install     'cross-env',
5 verbose install     'css-loader',
5 verbose install     'file-loader',
5 verbose install     'json-loader',
5 verbose install     'url-loader',
5 verbose install     'stylus-loader',
5 verbose install     'vue-hot-reload-api',
5 verbose install     'vue-html-loader',
5 verbose install     'vue-loader',
5 verbose install     'vue-style-loader',
5 verbose install     'webpack',
5 verbose install     'webpack-dev-server' ] ]
6 info preinstall wechat_bot@1.0.0
7 verbose readDependencies using package.json deps
8 verbose already installed skipping body-parser@^1.15.0 /home/<User>/Documents/wechatBot-master
9 verbose already installed skipping debug@^2.2.0 /home/<User>/Documents/wechatBot-master
10 verbose already installed skipping es6-promise@^3.1.2 /home/<User>/Documents/wechatBot-master
11 verbose already installed skipping express@^4.13.4 /home/<User>/Documents/wechatBot-master
12 verbose already installed skipping jade@^1.11.0 /home/<User>/Documents/wechatBot-master
13 verbose already installed skipping vue@^1.0.16 /home/<User>/Documents/wechatBot-master
14 verbose already installed skipping vue-resource@^0.7.0 /home/<User>/Documents/wechatBot-master
15 verbose already installed skipping vue-router@^0.7.11 /home/<User>/Documents/wechatBot-master
16 verbose already installed skipping vue-strap@^1.0.7 /home/<User>/Documents/wechatBot-master
17 verbose already installed skipping wechat4u@^0.3.0 /home/<User>/Documents/wechatBot-master
18 verbose already installed skipping babel-core@^6.0.0 /home/<User>/Documents/wechatBot-master
19 verbose already installed skipping babel-loader@^6.0.0 /home/<User>/Documents/wechatBot-master
20 verbose already installed skipping babel-plugin-transform-runtime@^6.0.0 /home/<User>/Documents/wechatBot-master
21 verbose already installed skipping babel-preset-es2015@^6.0.0 /home/<User>/Documents/wechatBot-master
22 verbose already installed skipping babel-preset-stage-2@^6.0.0 /home/<User>/Documents/wechatBot-master
23 verbose already installed skipping babel-runtime@^5.8.0 /home/<User>/Documents/wechatBot-master
24 verbose already installed skipping cross-env@^1.0.6 /home/<User>/Documents/wechatBot-master
25 verbose already installed skipping css-loader@^0.23.0 /home/<User>/Documents/wechatBot-master
26 verbose already installed skipping file-loader@^0.8.4 /home/<User>/Documents/wechatBot-master
27 verbose already installed skipping json-loader@^0.5.4 /home/<User>/Documents/wechatBot-master
28 verbose already installed skipping url-loader@^0.5.7 /home/<User>/Documents/wechatBot-master
29 verbose already installed skipping stylus-loader@^1.4.0 /home/<User>/Documents/wechatBot-master
30 verbose already installed skipping vue-hot-reload-api@^1.2.0 /home/<User>/Documents/wechatBot-master
31 verbose already installed skipping vue-html-loader@^1.0.0 /home/<User>/Documents/wechatBot-master
32 verbose already installed skipping vue-loader@^8.0.0 /home/<User>/Documents/wechatBot-master
33 verbose already installed skipping vue-style-loader@^1.0.0 /home/<User>/Documents/wechatBot-master
34 verbose already installed skipping webpack@^1.12.2 /home/<User>/Documents/wechatBot-master
35 verbose already installed skipping webpack-dev-server@^1.12.0 /home/<User>/Documents/wechatBot-master
36 verbose already installed skipping axios@^0.9.1 /home/<User>/Documents/wechatBot-master
37 silly resolved []
38 info build /home/<User>/Documents/wechatBot-master
39 verbose linkStuff [ false, false, false, '/home/<User>/Documents' ]
40 info linkStuff wechat_bot@1.0.0
41 verbose linkBins wechat_bot@1.0.0
42 verbose linkMans wechat_bot@1.0.0
43 verbose rebuildBundles wechat_bot@1.0.0
44 verbose rebuildBundles [ '.bin',
44 verbose rebuildBundles   'axios',
44 verbose rebuildBundles   'babel-core',
44 verbose rebuildBundles   'babel-loader',
44 verbose rebuildBundles   'babel-plugin-transform-runtime',
44 verbose rebuildBundles   'babel-preset-es2015',
44 verbose rebuildBundles   'babel-preset-stage-2',
44 verbose rebuildBundles   'babel-runtime',
44 verbose rebuildBundles   'body-parser',
44 verbose rebuildBundles   'cross-env',
44 verbose rebuildBundles   'css-loader',
44 verbose rebuildBundles   'debug',
44 verbose rebuildBundles   'es6-promise',
44 verbose rebuildBundles   'express',
44 verbose rebuildBundles   'file-loader',
44 verbose rebuildBundles   'jade',
44 verbose rebuildBundles   'json-loader',
44 verbose rebuildBundles   'stylus-loader',
44 verbose rebuildBundles   'url-loader',
44 verbose rebuildBundles   'vue',
44 verbose rebuildBundles   'vue-hot-reload-api',
44 verbose rebuildBundles   'vue-html-loader',
44 verbose rebuildBundles   'vue-loader',
44 verbose rebuildBundles   'vue-resource',
44 verbose rebuildBundles   'vue-router',
44 verbose rebuildBundles   'vue-strap',
44 verbose rebuildBundles   'vue-style-loader',
44 verbose rebuildBundles   'webpack',
44 verbose rebuildBundles   'webpack-dev-server',
44 verbose rebuildBundles   'wechat4u' ]
45 info install wechat_bot@1.0.0
46 info postinstall wechat_bot@1.0.0
47 info prepublish wechat_bot@1.0.0
48 error peerinvalid The package babel-runtime does not satisfy its siblings' peerDependencies requirements!
48 error peerinvalid Peer vue-loader@8.5.2 wants babel-runtime@^6.0.0
49 error System Linux 3.10.0-229.1.2.el7.x86_64
50 error command "node" "/usr/bin/npm" "install"
51 error cwd /home/<User>/Documents/wechatBot-master
52 error node -v v0.10.42
53 error npm -v 1.3.6
54 error code EPEERINVALID
55 verbose exit [ 1, true ]

**Comment by stonexer** [comment]
vue-loader@8.5.2 wants babel-runtime@^6.0.0

试下 npm update ，还不行的话直接把 package.json 里的 babel-runtime 改成 ^6.0.0 再 npm install 吧

**Comment by cbwang2016** [comment]
改了package.json后解决了
然而npm run build又报了这个错：
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./public/javascripts/src/components/LoginView.vue
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home//Documents/wechatBot-master/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home//Documents/wechatBot-master/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home//Documents/wechatBot-master/node_modules/vue-loader/lib/style-rewriter.js:101:6)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./public/javascripts/src/components/LoginView.vue 4:14-222

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./public/javascripts/src/components/Member.vue
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home//Documents/wechatBot-master/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home//Documents/wechatBot-master/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home//Documents/wechatBot-master/node_modules/vue-loader/lib/style-rewriter.js:101:6)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./public/javascripts/src/components/Member.vue 4:14-269

**Comment by stonexer** [comment]
我的问题，太久没更新了。可以测试下 checkout 到最新 commit，删掉原来的 node_modules 重新 npm install 么。

**Comment by cbwang2016** [comment]
还是不行……类似的错误

**Comment by stonexer** [comment]
node version 呢？似乎是 css-loader 和 node 版本的兼容性问题

https://github.com/webpack/css-loader/issues/145

**Comment by cbwang2016** [comment]
好吧...应该是这个问题，我现在node是0.10.42

**Comment by cbwang2016** [comment]
已解决问题，node更新至6.2.1就行了
