### ISSUE TITLE
登录失败，不能显示二维码

### ISSUE THREAD

**Issue by spacelan** [stonexer/wechatBot#9]
![baidushurufa_2016-3-2_11-21-11](https://cloud.githubusercontent.com/assets/3382212/13449714/21a581ea-e069-11e5-8b86-ae7d03a1c5bb.png)

出现这种情况只有手动删除local storage才行？

**Comment by stonexer** [comment]
大哥，我就是因为这个才需要赶紧加上 state... 要不然没法判断状态

**Comment by stonexer** [comment]
@spacelan 大哥，我临时改了下服务器端的wechat4u，应该没这个bug了
